import test from 'node:test';
import assert from 'node:assert/strict';
import { createSafeUgServer } from './server.mjs';

test('mobile signal, admin status, duplicate retry and records share one database', async () => {
  const server = createSafeUgServer(':memory:',{adminPassword:'test-password-only'});
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  let authorization={};
  const request = async (path, method = 'GET', body) => fetch(base + path, {method, headers: {'Content-Type':'application/json',...authorization}, body: body ? JSON.stringify(body) : undefined});
  try {
    assert.equal((await request('/api/state')).status,401);
    assert.equal((await request('/api/auth/login','POST',{username:'wrong-admin',password:'test-password-only'})).status,401);
    const login=await request('/api/auth/login','POST',{username:'admin',password:'test-password-only'});
    assert.equal(login.status,200);
    const admin={Cookie:login.headers.get('set-cookie').split(';')[0]};
    const device=await (await request('/api/auth/device','POST')).json();
    const mobile={Authorization:`Bearer ${device.token}`};
    authorization=mobile;
    const profile={name:'Test Tourist',phone:'+256 700 123456',email:'tourist@example.test',area:'Test park',country:'Uganda',emergencyContactName:'Test Contact',emergencyContactPhone:'+256700654321',consent:true,status:'Resolved',ownerId:'spoof'};
    assert.equal((await request('/api/tourist-profile','PUT',{...profile,consent:false})).status,400);
    assert.equal((await request('/api/tourist-profile','PUT',{...profile,email:'bad'})).status,400);
    assert.equal((await request('/api/tourist-profile','PUT',profile)).status,201);
    const tourist=await (await request('/api/tourist-profile','PUT',profile)).json();
    assert.equal(tourist.ownerId,device.id);
    assert.equal(tourist.status,'Active');
    assert.equal((await (await request('/api/state')).json()).tourists.length,1);
    authorization=admin;
    const adminTourists=(await (await request('/api/state')).json()).tourists;
    assert.equal(adminTourists.length,1);
    assert.equal(adminTourists[0].emergencyContactPhone,profile.emergencyContactPhone);
    assert.equal((await request(`/api/tourists/${tourist.id}`,'PATCH',{status:'Needs attention'})).status,200);
    authorization=mobile;
    const updated=await (await request('/api/tourist-profile','PUT',{...profile,name:'Updated Tourist'})).json();
    assert.equal(updated.id,tourist.id);
    assert.equal(updated.status,'Needs attention');
    assert.equal((await request('/api/tourists','POST',profile)).status,403);
    assert.equal((await request('/api/guides','POST',{name:'Unapproved guide'})).status,403);
    const signal = {id:'test-sos',type:'SOS',latitude:0.31,longitude:32.58};
    assert.equal((await request('/api/incidents','POST',signal)).status,201);
    assert.equal((await request('/api/incidents/test-sos','PATCH',{status:'Resolved'})).status,403);
    const other=await (await request('/api/auth/device','POST')).json();
    authorization={Authorization:`Bearer ${other.token}`};
    assert.equal((await (await request('/api/state')).json()).tourists.length,0);
    assert.equal((await request(`/api/tourists/${tourist.id}`,'PATCH',profile)).status,403);
    assert.equal((await (await request('/api/state')).json()).incidents.length,0);
    assert.equal((await request('/api/incidents','POST',signal)).status,403);
    authorization=admin;
    assert.equal((await request('/api/incidents/test-sos','PATCH',{status:'Acknowledged'})).status,200);
    authorization=mobile;
    const retry = await request('/api/incidents','POST',signal);
    assert.equal((await retry.json()).status,'Acknowledged');
    const state = await (await request('/api/state')).json();
    assert.equal(state.incidents.length,1);
    assert.equal(state.incidents[0].latitude,0.31);
    authorization=admin;
    assert.equal((await request('/api/guides','POST',{name:'Published guide',status:'Active'})).status,201);
    assert.equal((await request('/api/guides','POST',{name:'Hidden guide',status:'Inactive'})).status,201);
    assert.equal((await request('/api/rangers','POST',{name:'Test ranger',area:'Test park',status:'On patrol'})).status,201);
    assert.equal((await (await request('/api/state')).json()).rangers.length,1);
    assert.equal((await request('/api/incidents/test-sos','PATCH',{status:'invented'})).status,400);
    assert.equal((await request('/api/incidents','POST',{id:'bad-gps',latitude:99})).status,400);
    assert.equal((await request('/api/rangers/missing','PATCH',{name:'Missing'})).status,404);
    authorization=mobile;
    const visible=await (await request('/api/state')).json();
    assert.equal(visible.guides.length,1);
    assert.equal(visible.rangers.length,0);
    assert.equal((await request('/api/translate','POST',{q:'Help',source:'en',target:'sw'})).status,503);
    assert.equal((await request('/api/dispatch/test-sos','POST',{})).status,403);
    authorization=admin;
    assert.equal((await request('/api/dispatch/test-sos','POST',{})).status,503);
    const media={id:'with-evidence',type:'Poaching',description:'Suspected poaching near the park entrance.',area:'Park entrance',evidence:[{name:'pixel.png',mime:'image/png',base64:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg=='},{name:'header-fixture.mp4',mime:'video/mp4',base64:Buffer.from([0,0,0,12,102,116,121,112,109,112,52,50]).toString('base64')}]};
    authorization=mobile;
    const saved=await (await request('/api/incidents','POST',media)).json();
    const evidenceId=saved.evidence[0].id;
    assert.equal(saved.evidence.length,2);
    assert.equal((await request(`/api/evidence/${evidenceId}`)).status,200);
    authorization={Authorization:`Bearer ${other.token}`};
    assert.equal((await request(`/api/evidence/${evidenceId}`)).status,404);
    authorization=admin;
    assert.equal((await request(`/api/evidence/${evidenceId}`)).status,200);
    const video=await request(`/api/evidence/${saved.evidence[1].id}`);
    assert.equal(video.status,200);
    assert.equal(video.headers.get('content-type'),'video/mp4');
    assert.equal((await request('/api/incidents','POST',{type:'Poaching',description:'Suspected poaching near the park entrance.',area:'Park entrance',evidence:[{name:'fake.png',mime:'image/png',base64:'SGVsbG8='}]})).status,400);
    assert.equal((await request('/api/auth/logout','POST',{})).status,200);
    assert.equal((await request('/api/state')).status,401);
    assert.equal((await fetch(base+'/api/state',{headers:{Origin:'https://untrusted.example'}})).status,403);
  } finally { await new Promise(resolve => server.close(resolve)); }
});

test('incident contract preserves SMART reports and audits verified SOS responses', async () => {
  const server=createSafeUgServer(':memory:',{adminPassword:'test-password-only',seedContacts:false});
  await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
  const base=`http://127.0.0.1:${server.address().port}`;
  const request=(auth,path,method='GET',body) => fetch(base+path,{method,headers:{'Content-Type':'application/json',...auth},body:body===undefined?undefined:JSON.stringify(body)});
  try {
    const login=await request({},'/api/auth/login','POST',{username:'admin',password:'test-password-only'});
    const admin={Cookie:login.headers.get('set-cookie').split(';')[0]};
    const device=await (await request({},'/api/auth/device','POST')).json();
    const mobile={Authorization:`Bearer ${device.token}`};
    const otherDevice=await (await request({},'/api/auth/device','POST')).json();
    const other={Authorization:`Bearer ${otherDevice.token}`};
    const occurredAt=new Date(Date.now()-60*1000).toISOString();
    const report={id:'smart-report',type:'suspicious activity',area:'Park north gate',description:'Two unknown people cutting the fence near the gate.',severity:'High',occurredAt,reporter:'Guest reporter',phone:'+256700123456',latitude:0.31,longitude:32.58,accuracy:7,locationCapturedAt:'2026-09-30T07:31:00Z',locationSource:'device',status:'Dispatched',responseAgency:'Forged police contact',responseNote:'Spoofed response',externalDelivery:'Submitted',statusHistory:[{status:'Dispatched'}],ownerId:'forged'};
    const createdResponse=await request(mobile,'/api/incidents','POST',report);
    assert.equal(createdResponse.status,201);
    const created=await createdResponse.json();
    assert.equal(created.type,'Suspicious Activity');
    assert.equal(created.severity,'High');
    assert.equal(created.occurredAt,occurredAt);
    assert.equal(created.locationCapturedAt,'2026-09-30T07:31:00.000Z');
    assert.equal(created.status,'Reported');
    assert.equal(created.ownerId,device.id);
    assert.equal(created.responseAgency,undefined);
    assert.equal(created.externalDelivery,undefined);
    assert.deepEqual(created.statusHistory.map(item=>[item.status,item.actor]),[['Reported','mobile']]);
    const visible=(await (await request(admin,'/api/state')).json()).incidents[0];
    for(const field of ['description','area','severity','reporter','phone','latitude','longitude','accuracy','locationSource']) assert.equal(visible[field],created[field]);
    for(const type of ['Animal Sighting','Safety Hazard','Human-Wildlife Conflict','Illegal Encroachment','Other']) {
      const response=await request(mobile,'/api/incidents','POST',{...report,id:undefined,type});
      assert.equal(response.status,201,type);
    }
    for(const changes of [{severity:'Urgent'},{type:'Unknown category'},{occurredAt:'yesterday'},{occurredAt:new Date(Date.now()+10*60*1000).toISOString()},{locationCapturedAt:'not-a-date'},{accuracy:-1},{phone:'not a phone'},{latitude:null},{locationSource:'manual-coordinates'},{description:'   '},{area:' ',latitude:null,longitude:null,locationSource:'unavailable'}]) {
      assert.equal((await request(mobile,'/api/incidents','POST',{...report,id:undefined,...changes})).status,400,JSON.stringify(changes));
    }
    assert.equal((await request(mobile,'/api/incidents','POST',{type:'Other',description:'A fallen tree is blocking the path.',area:'East walking trail'})).status,201);
    assert.equal((await request(mobile,'/api/incidents','POST',{type:'Animal Sighting',description:'An elephant is crossing the trail.',latitude:0.31,longitude:32.58})).status,201);
    const legacy=await (await request(admin,'/api/incidents','POST',{type:'SOS',id:'legacy-incomplete'})).json();
    assert.equal(legacy.description,undefined);
    // Existing incomplete records remain operable; only new non-SOS reports
    // require description and a location/landmark.
    assert.equal((await request(admin,'/api/incidents/legacy-incomplete','PATCH',{type:'Other',status:'Acknowledged'})).status,200);
    assert.equal((await request(mobile,'/api/incidents/smart-report/location','POST',{})).status,400);
    const sos=await (await request(mobile,'/api/incidents','POST',{id:'active-sos',type:'SOS Activation'})).json();
    assert.equal(sos.type,'SOS');
    assert.equal(sos.severity,'Critical');
    const location={latitude:0.33,longitude:32.6,accuracy:5,locationCapturedAt:'2026-09-30T08:00:00Z'};
    assert.equal((await request(other,'/api/incidents/active-sos/location','POST',location)).status,403);
    const located=await (await request(mobile,'/api/incidents/active-sos/location','POST',location)).json();
    assert.equal(located.latitude,location.latitude);
    assert.equal(located.locationHistory.length,1);
    const retry=await (await request(mobile,'/api/incidents/active-sos/location','POST',location)).json();
    assert.equal(retry.locationHistory.length,1);
    const acknowledged=await (await request(admin,'/api/incidents/active-sos','PATCH',{status:'Acknowledged',responseAgency:'Operations desk',responseNote:'Operator reviewing the alert.'})).json();
    assert.equal(acknowledged.responseAgency,'Operations desk');
    assert.deepEqual(acknowledged.statusHistory.map(item=>item.status),['Reported','Acknowledged']);
    const unchanged=await (await request(admin,'/api/incidents/active-sos','PATCH',{status:'Acknowledged'})).json();
    assert.equal(unchanged.statusHistory.length,2);
    assert.equal((await request(other,'/api/incidents/active-sos/stand-down','POST',{reason:'I am safe / accidental activation'})).status,403);
    assert.equal((await request(mobile,'/api/incidents/active-sos/stand-down','POST',{reason:'invented'})).status,400);
    const closed=await (await request(mobile,'/api/incidents/active-sos/stand-down','POST',{reason:'I am safe / accidental activation',status:'Dispatched'})).json();
    assert.equal(closed.status,'False Alarm');
    assert.equal(closed.statusHistory.at(-1).actor,'mobile');
    assert.ok(closed.resolvedAt);
    const closeRetry=await (await request(mobile,'/api/incidents/active-sos/stand-down','POST',{reason:'I am safe / accidental activation'})).json();
    assert.equal(closeRetry.statusHistory.length,3);
    const lateLocation=await (await request(mobile,'/api/incidents/active-sos/location','POST',{...location,latitude:1,locationCapturedAt:'2026-09-30T09:00:00Z'})).json();
    assert.equal(lateLocation.status,'False Alarm');
    assert.equal(lateLocation.latitude,location.latitude);
  } finally { await new Promise(resolve => server.close(resolve)); }
});
