import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Firebase configuration for the SafeUG project.
///
/// The project currently has a registered Web Firebase app. The same project
/// credentials are used as a development fallback for mobile builds so the
/// app can run immediately. Before publishing, run `flutterfire configure`
/// and replace the Android and iOS entries with the native app registrations.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'SafeUG Firebase is not configured for this platform.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyBwrxwwqyKwwEL4B0bM4rFMfaf1ufqBLWA',
    appId: '1:749243940919:web:89557c44104e201c9affb2',
    messagingSenderId: '749243940919',
    projectId: 'studio-4293160039-89d0f',
    authDomain: 'studio-4293160039-89d0f.firebaseapp.com',
  );

  // Temporary development fallback. Native Firebase app IDs should be
  // generated by FlutterFire before the Android/iOS release is published.
  static const android = FirebaseOptions(
    apiKey: 'AIzaSyBwrxwwqyKwwEL4B0bM4rFMfaf1ufqBLWA',
    appId: '1:749243940919:web:89557c44104e201c9affb2',
    messagingSenderId: '749243940919',
    projectId: 'studio-4293160039-89d0f',
  );

  static const ios = FirebaseOptions(
    apiKey: 'AIzaSyBwrxwwqyKwwEL4B0bM4rFMfaf1ufqBLWA',
    appId: '1:749243940919:web:89557c44104e201c9affb2',
    messagingSenderId: '749243940919',
    projectId: 'studio-4293160039-89d0f',
    iosBundleId: 'com.safeug.app',
  );
}
